---
title: "Practice9"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
mystery_animal <- read_csv(here::here('supporting_artifacts', 'PracticeActivityWeek9', 'mystery_animal.csv'))
```

```{r}
mystery_animal |> mutate(ate = 1)  |>
  lm(weight_after ~ weight_before, data = _) |>
  broom::augment() |>
  ggplot(mapping = aes(x = .fitted, y = .resid)) + geom_point()
```

# 2 Warm-up

-   What is the 95th percentile for trumpet weight?

    ```{r}
    qnorm(.95, mean = 4.6, sd = .8)
    ```

-   What is the 10th percentile for trombone weight?

    ```{r}
    qnorm(.1, mean = 4.6, sd = .8)
    ```

```{r}
music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  summ <- sum(trombones) + sum(cornets) + sum(reeds)
  return(summ)
  
}

set.seed(1957)

my_weights <- rerun(.n = 1000, 
                    music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                    ) |> 
  flatten_dbl()
sum(my_weights < 4532)
```
