<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sebastian Boksem">

<title>Lab3: Hip-Hop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Lab3_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lab3_files/libs/quarto-html/quarto.js"></script>
<script src="Lab3_files/libs/quarto-html/popper.min.js"></script>
<script src="Lab3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lab3_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lab3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lab3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lab3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lab3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lab3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab3: Hip-Hop</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sebastian Boksem </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="part-1-instructions" class="level2">
<h2 class="anchored" data-anchor-id="part-1-instructions">Part 1, Instructions</h2>
<p>Declaring Libraries</p>
<div class="cell" data-execute="{}">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Importing Data Set</p>
<div class="cell" data-execute="{}">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hiphop <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"supporting_artifacts"</span>, <span class="st">"Lab3"</span>, <span class="st">"hiphop.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="part-3-assignment" class="level2">
<h2 class="anchored" data-anchor-id="part-3-assignment">Part 3, Assignment</h2>
<p>1.</p>
<p><strong>REFELCTION:</strong></p>
<p><strong>Upon looking back on this question, it made me realize that I did not answer essential parts about the data we were in question about. This is of course important when later analyzing it, to be able to get the bigger picture and what potential outcomes could be. I now know for the future to also take into account participants coding and how it could vary across data sets.</strong></p>
<div class="cell" data-execute="{}">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hiphop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>his study takes a deeper look at African-American English (AAE) with asking students from the University of Minnesota familiarity of different vocabulary words. All the data seems to be in either characters, or numbers. There also seems to be some people in the study where key columns are not recorded for, like city being 0. There is overall 10752 rows and 38 variables in total. The participants were selected from undergraduate linguistics, sociology, and music classes and contains 168 participants. The participants were coded as “p” following by their respective participant number, overall being a character string.</p>
<p>2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hiphop <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(word, subj) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10752</code></pre>
</div>
</div>
<p>There are 10752 rows in this data set. This is due to there being 168 people and 64 words. so for each word, 168 people (or rows) will be answering it.</p>
<p>3.</p>
<p><strong>REFELCTION:</strong></p>
<p><strong>Upon looking back on this question, it made me more away to take a glance at the meta data about the lab. I think after reflecting on this it overall allowed me to better understand the data set that was in use and as a result better understand the data analytics-techniques that we used here. I will now continue to inspect the data before I use it in the future.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>hiphop <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(city <span class="sc">==</span> <span class="dv">0</span>, county <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 384 × 38
   word    subj  sex     age ethnic  city county  intl vocal class…¹  folk  rock
   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 [to be… p145  Male     18 white      0      0     0     0       0     0    15
 2 [to be… p147  Fema…    20 asian      0      0     0     0       4     0     0
 3 [to be… p11   Fema…    18 asian      0      0    15     0       0     0     0
 4 [to be… p43   Fema…    18 asian      0      0     6     0       0     0     0
 5 [to be… p135  Fema…    18 asian      0      0     0     0       3     0     0
 6 [to be… p81   Fema…    18 asian      0      0     0     0       2     0     0
 7 5-0     p145  Male     18 white      0      0     0     0       0     0    15
 8 5-0     p147  Fema…    20 asian      0      0     0     0       4     0     0
 9 5-0     p11   Fema…    18 asian      0      0    15     0       0     0     0
10 5-0     p43   Fema…    18 asian      0      0     6     0       0     0     0
# … with 374 more rows, 26 more variables: country &lt;dbl&gt;, pop &lt;dbl&gt;,
#   alternative &lt;dbl&gt;, hiphop &lt;dbl&gt;, unclassifiable &lt;dbl&gt;, countyBlack &lt;dbl&gt;,
#   jayz &lt;dbl&gt;, barkley &lt;dbl&gt;, boondocks &lt;dbl&gt;, monique &lt;dbl&gt;, bieber &lt;dbl&gt;,
#   asianMove &lt;dbl&gt;, blackMove &lt;dbl&gt;, hispanicMove &lt;dbl&gt;, nativeMove &lt;dbl&gt;,
#   SAAMEMove &lt;dbl&gt;, whiteMove &lt;dbl&gt;, blackWeekly &lt;dbl&gt;, jayz1 &lt;dbl&gt;,
#   boondocks1 &lt;dbl&gt;, familiarity &lt;dbl&gt;, trial &lt;dbl&gt;, fam1 &lt;dbl&gt;,
#   popularityScore &lt;dbl&gt;, numPreferredArtists &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>It seems like for some of the variables were replaced with 0 instead of NA values, such as some subjects data in city and county. This could be beneficial because they would still represent specific points in the data set, without potentially needing to remove them. A drawback however is that when using summary statistics they would be accounted for instead which might drop down the mean/median without knowing it would do so. Another way they replaced missing values for SAAMEMove and BlackWeekly would be instead of 0 they just had the mean value (0.2948718). This as a result could be beneficial because it is representative of the sample population instead of 0. However this would not be helpful when calculating further summary statistics for one of these two categories because the mean or median could be biased.</p>
<p>4.</p>
<p><strong>REFELCTION:</strong></p>
<p><strong>This question made me more aware of the functionality of the across function. Initially, I tended to stray away from using the across() function because I didn’t understand the syntax too well. However, after I now understand how to use it and will in future labs.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Clean the data set</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="ot">&lt;-</span> hiphop <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(sex, ethnic, jayz1, fam1, boondocks1), <span class="at">.fns =</span> as.factor</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                )) <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(city <span class="sc">!=</span> <span class="dv">0</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>         county <span class="sc">!=</span> <span class="dv">0</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>         countyBlack <span class="sc">!=</span> <span class="dv">0</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>hiphop <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">distinct</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 64</code></pre>
</div>
</div>
<p>There are 64 unique AAE words that were studied in this data set.</p>
<p>6.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="ot">&lt;-</span> hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ethnic1 =</span> <span class="fu">if_else</span>(ethnic <span class="sc">==</span> <span class="st">'white'</span>, <span class="st">'white'</span>, <span class="st">'non-white'</span>),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ethnic1 =</span> <span class="fu">as.factor</span>(ethnic1)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>7.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(subj, age, ethnic, sex) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     subj               sex           age             ethnic   
 Length:159         Female:109   Min.   :16.00   white   :133  
 Class :character   Male  : 50   1st Qu.:18.00   asian   : 14  
 Mode  :character                Median :19.00   african :  5  
                                 Mean   :20.12   indian  :  2  
                                 3rd Qu.:20.00   biracial:  1  
                                 Max.   :48.00   black   :  1  
                                                 (Other) :  3  </code></pre>
</div>
</div>
<p>In this data set, there seems to be an age range between 16 and 48 with the median being 19 (Overall predictable for a study done in a college class). For ethnicity, there seems to be a majority white with 133 students, followed by asian with 14 students. For sex, the class seems to be predominately female with 109 students, followed by male with 50. This also takes into account the clean data set.</p>
<p>8.</p>
<p><strong>REFELCTION GRAPH 1:</strong></p>
<p><strong>Upon looking back on this question, it made me understand to give a deeper look into my graphs after I run them, not just simply code it and render it later. I think initially I just ran it but didn’t see the labels and notice the mistake. I know now for the future to pay more attention to the x and y axis labels</strong></p>
<p><strong>REFELCTION GRAPH 2:</strong></p>
<p><strong>Upon looking back on this question, and changing my graph, it allowed me to look into more graphs that could help me visualize any data. This was even more helpful because it allowed me to go back to the challenge problem and see how I could incorporate it into this set as well. I hopefully will be continuing to use these graphs in the future.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> hiphopclean, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> age,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> ethnic,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                     )) <span class="sc">+</span> </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"Ethnicity"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> age,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">y =</span> ethnic,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                                   )) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>(<span class="at">width =</span> <span class="fl">0.5</span>, <span class="at">panel_scaling =</span> <span class="cn">FALSE</span>)  <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">y =</span> <span class="st">"Ethnicity"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Ignoring unknown parameters: width</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Picking joint bandwidth of 5.4</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab3_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="familiar-words" class="level2">
<h2 class="anchored" data-anchor-id="familiar-words">FAMILIAR WORDS</h2>
</section>
<section id="people-below-the-age-of-20" class="level2">
<h2 class="anchored" data-anchor-id="people-below-the-age-of-20">People below the age of 20</h2>
<p>Max: <strong>5-0, feel me, hella, off the hook</strong></p>
<p><strong>REFELCTION:</strong></p>
<p><strong>In this question I removed the arrange() that I initially put. I now know for the future to only input the code into questions that you ask about. I think initially when I was doing the lab, I just added it to visualize the arrange function better. However, I should have taken it out before I rendered the document. I have removed it for the other questions as well.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">20</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">fammed =</span> <span class="fu">median</span>(familiarity)) <span class="sc">|&gt;</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_max</span>(fammed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  word         fammed
  &lt;chr&gt;         &lt;dbl&gt;
1 5-0               5
2 feel me           5
3 hella             5
4 off the hook      5</code></pre>
</div>
</div>
<p>Min: <strong>ghost, A-town, ay yo trip, beezy, bones, boughie, break someone out, chedda, cheese</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">20</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">fammed =</span> <span class="fu">median</span>(familiarity)) <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_min</span>(fammed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 × 2
   word              fammed
   &lt;chr&gt;              &lt;dbl&gt;
 1 [to be] ghost          1
 2 A-town                 1
 3 ay yo trip             1
 4 beezy                  1
 5 bones                  1
 6 boughie                1
 7 break someone out      1
 8 catch the vapors       1
 9 chedda                 1
10 cheese                 1
# … with 46 more rows</code></pre>
</div>
</div>
</section>
<section id="non-white-women" class="level2">
<h2 class="anchored" data-anchor-id="non-white-women">Non-white women</h2>
<p>Max: <strong>A-town, boo, feel me, finna, off the hook, what it do</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">'Female'</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>       ethnic1 <span class="sc">==</span> <span class="st">'non-white'</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">fammed =</span> <span class="fu">median</span>(familiarity)) <span class="sc">|&gt;</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_max</span>(fammed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  word         fammed
  &lt;chr&gt;         &lt;dbl&gt;
1 A-town            5
2 boo               5
3 feel me           5
4 finna             5
5 off the hook      5
6 what it do        5</code></pre>
</div>
</div>
<p>Min: <strong>ghost, 5-0, ay yo trip, beezy, bones, boughie, break someone out, catch the vapors, chedda, cheese</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">'Female'</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>       ethnic1 <span class="sc">==</span> <span class="st">'non-white'</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">fammed =</span> <span class="fu">median</span>(familiarity)) <span class="sc">|&gt;</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_min</span>(fammed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 49 × 2
   word              fammed
   &lt;chr&gt;              &lt;dbl&gt;
 1 [to be] ghost          1
 2 5-0                    1
 3 ay yo trip             1
 4 beezy                  1
 5 bones                  1
 6 boughie                1
 7 break someone out      1
 8 catch the vapors       1
 9 chedda                 1
10 cheese                 1
# … with 39 more rows</code></pre>
</div>
</div>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="white-men-above-the-age-of-30" class="level2">
<h2 class="anchored" data-anchor-id="white-men-above-the-age-of-30">White men above the age of 30</h2>
<p>Max: <strong>5-0, A-town, feel me, hard, off the hook</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">'Male'</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>       ethnic1 <span class="sc">==</span> <span class="st">'white'</span>, </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>       age <span class="sc">&gt;</span> <span class="dv">30</span>) <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">fammed =</span> <span class="fu">median</span>(familiarity)) <span class="sc">|&gt;</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_max</span>(fammed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  word         fammed
  &lt;chr&gt;         &lt;dbl&gt;
1 5-0               5
2 A-town            5
3 feel me           5
4 hard              5
5 off the hook      5</code></pre>
</div>
</div>
<p>Min: <strong>ashy, ay yo trip, beezy, bones, boo, boughie, break someone out, catch the vapors, chedda, cheese</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">'Male'</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>       ethnic1 <span class="sc">==</span> <span class="st">'white'</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>       age <span class="sc">&gt;</span> <span class="dv">30</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">fammed =</span> <span class="fu">median</span>(familiarity)) <span class="sc">|&gt;</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_min</span>(fammed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 52 × 2
   word              fammed
   &lt;chr&gt;              &lt;dbl&gt;
 1 ashy                   1
 2 ay yo trip             1
 3 beezy                  1
 4 bones                  1
 5 boo                    1
 6 boughie                1
 7 break someone out      1
 8 catch the vapors       1
 9 chedda                 1
10 cheese                 1
# … with 42 more rows</code></pre>
</div>
</div>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
</section>
<section id="finding-bieber" class="level2">
<h2 class="anchored" data-anchor-id="finding-bieber">FINDING BIEBER:</h2>
<p>a white male, from a relatively small town (10,000-60,000 people) in Ontario would have been 17-23 at the time of the study.</p>
<p><strong>REFELCTION</strong></p>
<p><strong>Initially when I was doing this question, I did not understand the point of the group by and thought it had an effect if you used it at the end of the last pipe. I now know more about the relationship between group_by’s and summarize() and will continue to intertwine them in the future.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>hiphopclean <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">'Male'</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>       ethnic <span class="sc">==</span> <span class="st">'white'</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>       age <span class="sc">&gt;=</span> <span class="dv">17</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>       age <span class="sc">&lt;=</span> <span class="dv">23</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>       city <span class="sc">&gt;=</span> <span class="dv">10000</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>       city <span class="sc">&lt;=</span> <span class="dv">60000</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>       bieber <span class="sc">&gt;=</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(subj) <span class="sc">|&gt;</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  subj 
  &lt;chr&gt;
1 p17  </code></pre>
</div>
</div>
<p>I would assume that Justin Bieber would be person 17. adjusting for the factors above, and using the bieber variable to get the most Bieber listener, the person who stood out was p17. However, it is odd he did not know all his songs and get a score 6.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>